import { createDesk, matches, predict } from './domain.js';
import { createToolDefinitions, registerWebMCP } from './tools.js';

const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const desk=createDesk(render);
const tools=createToolDefinitions(desk);
window.__MATCHDAY_TOOLS__=tools;
let language='de';
const copy={
  de:{title:'Weniger Bauchgefühl.<br><em>Mehr Kontext.</em>',lede:'Ein erklärbarer Entscheidungsdesk, der Spiele vergleicht, Unsicherheit sichtbar macht und deine persönliche Watchlist baut.',cta:'Spiele analysieren',model:'Modell verstehen',modelCopy:'Teamstärke, Form, Angriff, Defensive und Volatilität — deterministisch gewichtet, ohne Black Box.',safety:'<span>✓ Keine Live-Wetten</span><span>✓ Keine Nutzerdaten</span>',lens:'Dein Blickwinkel',team:'Lieblingsteam',apply:'Ansicht anwenden',scenario:'Entscheidende Duelle',scenarioNote:'Prototype scenarios · keine Live-Daten oder Wettberatung',choose:'Wähle ein Spiel',chooseCopy:'Jede Prognose zeigt nicht nur das Ergebnis, sondern auch Unsicherheit und den stärksten Gegenfaktor.',selection:'DEINE AUSWAHL',empty:'Noch leer. Füge bis zu drei Spiele hinzu.',agentTitle:'Eine Oberfläche.<br>Acht klare Fähigkeiten.',agentCopy:'Die sichtbare UI und WebMCP verwenden dieselbe geprüfte Entscheidungslogik. Agenten müssen weder den DOM erraten noch versteckte Klickpfade nachahmen.',analyze:'Analyse',add:'＋ Watchlist',remove:'Entfernen',win:'Sieg',draw:'Unentschieden',why:'Warum dieses Signal?',counter:'Gegenfaktor',applied:'Ansicht aktualisiert — nur für diese Sitzung.'},
  en:{title:'Less guesswork.<br><em>More context.</em>',lede:'An explainable decision desk that compares matches, makes uncertainty visible, and builds your personal watchlist.',cta:'Analyze matches',model:'Understand the model',modelCopy:'Team strength, form, attack, defense, and volatility — weighted deterministically, without a black box.',safety:'<span>✓ No live betting</span><span>✓ No user data</span>',lens:'Your perspective',team:'Favorite team',apply:'Apply view',scenario:'Decisive matchups',scenarioNote:'Prototype scenarios · no live data or betting advice',choose:'Choose a match',chooseCopy:'Every prediction shows not only the result, but also uncertainty and its strongest counterfactor.',selection:'YOUR PICKS',empty:'Nothing here yet. Add up to three matches.',agentTitle:'One interface.<br>Eight clear capabilities.',agentCopy:'The visible UI and WebMCP share the same tested decision logic. Agents do not need to guess the DOM or imitate hidden click paths.',analyze:'Analyze',add:'＋ Watchlist',remove:'Remove',win:'win',draw:'Draw',why:'Why this signal?',counter:'Counterfactor',applied:'View updated — for this session only.'}
};

function card(match){const p=predict(match),c=copy[language];return `<article class="match-card" data-id="${esc(match.id)}"><div class="match-meta"><span>${esc(match.stage)}</span><span>${esc(match.kickoff)}</span></div><div class="teams"><div class="team"><span>${esc(match.home)}</span><span>${esc(match.homeCode)}</span></div><div class="team"><span>${esc(match.away)}</span><span>${esc(match.awayCode)}</span></div></div><div class="prediction"><div class="probability-row"><span>Model lean</span><span>${p.confidence}% confidence</span></div><strong>${esc(p.favorite)}</strong><div class="meter"><span style="width:${p.confidence}%"></span></div><div class="probability-row"><span>${p.homeWin}% · ${p.draw}% · ${p.awayWin}%</span><span>1 · X · 2</span></div></div><div class="card-actions"><button data-action="analyze">${c.analyze}</button><button data-action="shortlist">${desk.state.shortlist.includes(match.id)?c.remove:c.add}</button></div></article>`}
function analysis(match){const p=predict(match),e=desk.explain({match_id:match.id}),u=desk.upset({match_id:match.id}),c=copy[language];return `<p class="eyebrow">${esc(match.homeCode)} — ${esc(match.awayCode)} · MATCH EXPLAINER</p><h2>${esc(match.home)} <span class="muted">vs.</span> ${esc(match.away)}</h2><p>${esc(language==='en'?match.noteEn:match.note)}</p><div class="analysis-kpis"><div class="kpi"><strong>${p.homeWin}%</strong><span>${esc(match.home)} ${c.win}</span></div><div class="kpi"><strong>${p.draw}%</strong><span>${c.draw}</span></div><div class="kpi"><strong>${p.awayWin}%</strong><span>${esc(match.away)} ${c.win}</span></div></div><h3>${c.why}</h3><ul class="factor-list">${e.why.slice(0,2).map(x=>`<li>${esc(x)}</li>`).join('')}<li>Upset risk: ${esc(u.upsetRisk)} (${u.volatility}/100 volatility)</li></ul><p class="muted">${c.counter}: ${esc(e.counterfactor)}. Illustrative model only.</p>`}
function render(){
  const ordered=desk.list({risk_profile:desk.state.riskProfile});
  $('#match-grid').innerHTML=ordered.map(card).join('');
  const selected=desk.state.shortlist.map(id=>matches.find(m=>m.id===id));
  $('#shortlist-count').textContent=`${selected.length} / 3`;
  $('#shortlist').className=selected.length?'':'shortlist-empty';
  $('#shortlist').innerHTML=selected.length?selected.map(m=>`<div class="shortlist-item"><span><b>${esc(m.homeCode)} — ${esc(m.awayCode)}</b><br><small>${esc(predict(m).favorite)} · ${predict(m).confidence}%</small></span><button data-remove="${esc(m.id)}" aria-label="Remove ${esc(m.home)} versus ${esc(m.away)}">×</button></div>`).join(''):copy[language].empty;
}

function setLanguage(next){language=next;const c=copy[language];document.documentElement.lang=language;$('#language-toggle').textContent=language==='de'?'EN':'DE';$('#language-toggle').setAttribute('aria-label',language==='de'?'Switch to English':'Auf Deutsch wechseln');$('#hero-title').innerHTML=c.title;$('#hero-lede').textContent=c.lede;$('#primary-cta').textContent=c.cta;$('#explain-model').textContent=c.model;$('#model-copy').textContent=c.modelCopy;$('#safety-copy').innerHTML=c.safety;$('#lens-label').textContent=c.lens;$('#team-label').textContent=c.team;$('#save-preferences').textContent=c.apply;$('#scenario-title').textContent=c.scenario;$('#scenario-note').textContent=c.scenarioNote;const analysisTitle=$('#analysis-title'),analysisCopy=$('#analysis-copy');if(analysisTitle)analysisTitle.textContent=c.choose;if(analysisCopy)analysisCopy.textContent=c.chooseCopy;$('#shortlist-eyebrow').textContent=c.selection;$('#agent-title').innerHTML=c.agentTitle;$('#agent-copy').textContent=c.agentCopy;$('#risk-profile').options[0].textContent=language==='de'?'Ausgewogen':'Balanced';$('#risk-profile').options[1].textContent=language==='de'?'Favoriten zuerst':'Favorites first';$('#risk-profile').options[2].textContent=language==='de'?'Upset-Potenzial':'Upset potential';$('#favorite-team').options[0].textContent=language==='de'?'Kein Favorit':'No favorite';$('#preference-note').textContent=language==='de'?'Lokal für diese Sitzung — nichts wird gespeichert.':'Local to this session — nothing is stored.';render()}

for(const team of [...new Set(matches.flatMap(m=>[m.home,m.away]))].sort()){const option=document.createElement('option');option.value=team;option.textContent=team;$('#favorite-team').append(option)}
$('#match-grid').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const match=matches.find(m=>m.id===button.closest('.match-card').dataset.id);if(button.dataset.action==='analyze'){$('#analysis-panel').innerHTML=analysis(match);$('#analysis-panel').scrollIntoView({behavior:'smooth',block:'center'})}else desk.toggleShortlist(match.id)});
$('#shortlist').addEventListener('click',event=>{if(event.target.dataset.remove)desk.toggleShortlist(event.target.dataset.remove)});
$('#save-preferences').addEventListener('click',()=>{desk.setPreferences({risk_profile:$('#risk-profile').value,favorite_team:$('#favorite-team').value});$('#preference-note').textContent='Ansicht aktualisiert — nur für diese Sitzung.'});
$('#explain-model').addEventListener('click',()=>$('#model-dialog').showModal());
$('#language-toggle').addEventListener('click',()=>setLanguage(language==='de'?'en':'de'));
$('.dialog-close').addEventListener('click',()=>$('#model-dialog').close());
$('#tool-list').innerHTML=tools.map((tool,index)=>`<li>${String(index+1).padStart(2,'0')} · ${esc(tool.name)}<span>${tool.annotations.readOnlyHint?'READ':'LOCAL ACTION'}</span></li>`).join('');
render();
registerWebMCP(tools).then(result=>{$('#agent-status').textContent=result.available?`WebMCP ready · ${result.registered} tools`:'UI ready · WebMCP progressive enhancement'}).catch(()=>{$('#agent-status').textContent='UI ready · WebMCP registration unavailable'});
